FROM quay.io/jupyter/pytorch-notebook:cuda12-python-3.12
USER root

RUN apt update && apt install -y nvtop

RUN apt-get update && apt-get install -y wget gnupg && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt-get update && \
    apt-get install -y cuda-toolkit-12-8 && \
    rm cuda-keyring_1.1-1_all.deb

ENV CUDA_HOME=/usr/local/cuda
ENV PATH="${CUDA_HOME}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}"

USER ${NB_UID}

RUN python -m pip install --no-cache-dir --upgrade pip wheel setuptools

RUN python -m pip install --no-cache-dir bash_kernel && \
    python -m bash_kernel.install --sys-prefix

RUN python -m pip install --pre --no-cache-dir \
    lightning transformers datasets accelerate sentencepiece bitsandbytes peft && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN pip install --pre --no-cache-dir deepspeed && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN pip install --no-cache-dir \
    mlflow==2.13.0 \
    boto3==1.34.0 \
    optuna==3.6.1 \
    scikit-learn==1.4.2 \
    seqeval==1.2.2 \
    pyyaml==6.0.1 \
    nltk==3.8.1 && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

COPY --chown=${NB_UID}:${NB_GID} . /home/${NB_USER}/work/jitsi-training
