location = / {
    expires -1;
    add_header Cache-Control "no-store, no-cache, must-revalidate";
    try_files /index.html =404;
}

location = /index.html {
    expires -1;
    add_header Cache-Control "no-store, no-cache, must-revalidate";
}

location = /meeting-portal-ui.js {
    expires -1;
    add_header Cache-Control "no-store, no-cache, must-revalidate";
}

location = /meeting-portal-ui.css {
    expires -1;
    add_header Cache-Control "no-store, no-cache, must-revalidate";
}

location = /meeting-portal {
    return 302 /meeting-portal/;
}

location ^~ /meeting-portal/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_pass http://meeting-portal-app:8000;
}
